### ISSUE TITLE
What is the "encoding" process after extracting?

### ISSUE THREAD

**Issue by roizcorp** [flacon/flacon#103]
I'm not sure if the issue is correct or not but after the "split" of a given track from the big flac file there is another process of "encoding" which I fear re-encodes the audio file. (the flac settings in this regards are "same as source")

I thought that Flacon utilizes shnsplit just to "cut" tracks out of big flac album files according to cue files

**Comment by SokoloffA** [comment]
Flacon has not used shnsplit for a long time. The shnsplit has not been updated for a long time, and has problems with HD files.

Flacon has not used shntool for a long time. Shntool has not been updated for a long time, and has problems with HD files. 

Logic of the program so:
1. The Flacon start decode the big audio file to WAV.
2. Knowing the bitrate and sample rate of the original audio, I know how many bytes belongs to each track.  
3. I'm reading the this number of bytes of the track. If transcoding option is enabled, then I change the bitrate and/or sample rate of WAV data.
4. This data is saved to the per-track WAV files.
5. I encode per-track WAVs to the output format.

Even if you convert FLAC to FLAC. The algorithm is the same. Because:
1. It is easier to have one algorithm for all cases.
2. The input format may differ from the output format.
3. In the output format may have a different compression level settings then input file.
4. The program can change the bitrate and sample rate.

This should not cause you concerns, FLAC is a lossless format, so decoding and encoding does not spoil the sound at all.

**Comment by roizcorp** [comment]
Thank you for your answer, I am however concerned...I will look further for the shntool successor

**Comment by SokoloffA** [comment]
Shntool works similarly and more, all the utilities I know work like similarly. First decodes to WAV, and then encodes to the new format.

**Comment by roizcorp** [comment]
Thanks for the info, I was under the impression it does not, which is unfortunate. I hope you did not take it the wrong way, I really liked your GUI approach

**Comment by roizcorp** [comment]
I researched a little bit and it seems you are right, most of the tools do as yours, however I did find another tool that utilizes FFMPEG's atrim

**Comment by SokoloffA** [comment]
**Why do programs use this algorithm**

The logic is so. Suppose the first track has a length of 70 seconds. Then for CD quality, it has size: 
```
 2 channels * 16 bits per sample * 44100 samples per second * 70 seconds = 12348000 bytes
```

If we have uncompressed WAV, we can extract the second track just by reading the data with 12348000 bytes. But in compressed formats, the second takes a different number of bytes, so it is impossible to say from which byte will start 71 second.

**Using this algorithm is safe**
If you use the lossless format, the reencoding is safe. It's like using zip+unzip + zip+unzip, on output you get a bit-for-bit file on the output. But, everybody lies, so check it yourself:

0. Create a temporary directroy
```
$ mkdir ~/flacon_test
$ cp short.flac ~/flacon_test/test.flac
$ cd ~/flacon_test
```
1. We have an input Flac file. Calculate hash for it. 
```
$ shnhash test.flac
Hashing [test.flac] (3:39.07) : 100% OK
db4eb704807a9efe10b53e5c9249ee9a  [shntool]  test.flac
```
2. For test we create a CUE that contains one track.
```
$ echo 'FILE "test.wav" WAVE"' > test.cue
$ echo 'TRACK 01 AUDIO' >> test.cue
$ echo 'INDEX 00 00:00:00'  >> test.cue
```
3. We recode it via the Flacon.
```
$ flacon test.cue
```
4. Calculate the hash for results file.
```
$ cd YOUR_MUSIC_LIBRARY_DIRECTORY
shnhash *.flac
Hashing [01 - .flac] (3:39.07) : 100% OK
db4eb704807a9efe10b53e5c9249ee9a  [shntool]  01 - .flac
```

The hashes will match.

**Comment by roizcorp** [comment]
Thanks for the detailed information! I think that at the end the part that I was not aware of in compressed audio is that the data is not store in a linear, and now that I think of it - it makes sense! (cause otherwise how it would be compressed?!)
I did read some similar hash test which along with yours kind of quiet down my concerns
Thanks again!
