### ISSUE TITLE
In CLI mode some progress should be printed

### ISSUE THREAD

**Issue by marmistrz** [flacon/flacon#106]
One can run flacon in a command-line mode by invoking it as:
```
flacon file.cue -s
```
It would be extremely useful if flacon printed some progress, at least that it has started and finished converting a particular track.

**Comment by SokoloffA** [comment]
Unfortunately, I will not be able to show per track progress.  Since track processing consists of several stages (splitting, encoding and so on), the program processes tracks in a parallel manner and tracks have different duration. The maximum I can do is display a messages about started and finished converting a particular track.

**Comment by SokoloffA** [comment]
Supported in 6.0.0
