### ISSUE TITLE
RFC: Format or Profile in the combo box label. 

### ISSUE THREAD

**Issue by SokoloffA** [flacon/flacon#118]
Background, I added profiles in the new version. But on the main form, the field is still called "Format:".

In discussing another issue #105, @brainchild0 wrote:
>~I am now running version 6.0.0.  I have not found the new feature for profiles.  Where in the interface should I look for it?~ 
>I found the *add* and *remove* buttons in the preferences box, but I was confused because the word "format* is still in use (in the English version), though it now apparently means *profile*.

I tried to explain why I did it. 

> I did it on purpose. That's my logic:
> 
> * The program is many years old and it had a only formats list. 
> * Requests to add profiles are not frequent, most users are satisfied with a simple list of formats.
> * Most users use programs with default settings. By default, the program has one profile per format. So new profile list looks like previous format list.
> 
> In order not to confuse old users, I decided to have left the look and UX of the program as similar as possible to previous versions. If you don't add your own profiles, the program looks and works like before.
> 

But I'm not sure if this decision is best. Any ideas on this issue are welcome.

**Comment by brainchild0** [comment]
@SokoloffA: Now I understand better the rationale for the current structure.

Unfortunately, I personally find it confusing. Overall the interface for this application is simple, requiring very little learning.  It seems that trying to keep a visual design very close to the previous one should be a low priority, because users will be able to understand any new design that is also clear and simple.

General usage of this application falls into one of the following three categories:
1. Always use the same encoding format and option set.
1. Use various encoding formats, but always use the same option set for each format.
1. Use various encoding formats, and use more than one option set for at least one format.

The simplest case is (1). The most general is (3). Previously, the application supported (1) and (2).  In fact, the previous design, of saving the option set separately for each format,  directly expressed the requirements of (2). It provided some benefit over (1) without the generality of (3). 

However, (2) is not a common case.  Most usages will  be either (1) or (3). Now, profiles have added support for (3). With this enhancement, preserving a design that was created for case (2) may not be  helpful.  

I believe that if the application would  support directly, and in clear way, both (1) and (3), and indirectly support  (2), being a special case of (3), then the overall usability of the application would be greater than it has ever been previously.

**Comment by SokoloffA** [comment]
I think you've noticed that the functionality of all three cases already exists and works. If you create 2 profiles "Flac HD" and "Flac for phone", you  see both entries in the combobox on the main form. We are only talking about label text on the main form.

You were looking for a profile word because I wrote "Added support of profiles" in the changelog. If I wrote "Added support of saving a few settings for a format" you wouldn't be looking for the "profile" on GUI. 

If the user starts the program, they understand it's the audio program, so the first field is the path to the audio files, and the third is their format. But if he sees a "Profile", the question arises, the profile of what?

I'm not a native English speaker, but in Russian we can say "FLAC is a format", and we can say "FLAC 24bit 192khz is a format too". Both statements are correct, so I used it because it fits for both case 1 and 3. Now the "profile" word used only in the dialog of creating it. Perhaps will be better not use this word at all.

**Comment by brainchild0** [comment]
My comments are directed at the structure of the interface much more than the choice of words. The idea is that case (1) suggests a simple and natural layout for a dialog box, which may be enhanced to support both cases (2) and (3), where (2) is a special a case   requiring  no separate support.

Currently the structure is designed  around case (2), with a  generalization to case (3).  This layout feels unnatural to me. The reasoning you give is to preserve clarity and simplicity of use, but I believe that such clarity is possible  by considering only cases (1) and (3).

(In English I believe it is more natural to associate the word *format*, in the case of audio and video encoding, with the top-level classification, such as FLAC, Ogg, and so on. The distinction of format is  a question of what decoder is needed to play. Bitrate and sample rate are generally called _encoding options_, in my experience, and considered as separate from the choice of format. However, as I said, my comments emphasize layout not language.)

**Comment by SokoloffA** [comment]
OK, let's talk about the interface structure. Correct me if I'm wrong, this is how I represent standard use-case for 3 variant.

User have several devices. Let it will be a laptop, a phone and car audio. User want to have 3 collections in different directories with different quality.
* HD flac for laptop
* CD-quality flac for phone 
* and mp3 for car

I assume that:
1. The number of profiles will be small. A few, much less than a dozen.
2. The user does not need to frequently change the audio format for the device. It has chosen a format and encodes in it.

Therefore, I decided not to make a two-level profile-format structure, but to limit a flat list of profiles.

I see use case as:
The user creates a profile and selects a format for it. Later he select a profile with one click, and encode with the desired format and into desired directory. 
I see no reason why the user should frequently switch formats within the same profile. 

I may not understand your use case, then describe it. And what exactly you suggest to changing in the interface?

**Comment by SokoloffA** [comment]
Yes, I should add. This is convenient for me personally, I created a profile for my real music collection with a separate directory. I use the other profiles for tests. Now the test files are not mixed with my music.

**Comment by brainchild0** [comment]
I think that your use case is the same as mine, and I support your assumptions.

The difference in my thinking is that I find the current design conflates the following two separate categories of items:

- **Format**, meaning an encoding method specified by standards and implemented in software.
- **Profile**, meaning values for a set of options, saved locally for a user, and including the format.

Again, for me the issue is not which words are chosen to label each category, but simply that the categories are distinct.

Imagining how we might begin with a new design that has no history, we might choose one different from the current structure. Implementing it may require more work than you are currently considering, but it is worthwhile to evaluate which features we might include.

Basic steps for specifying an encoding scenario might be given as follows:

1. Choose a *format* (e.g. FLAC, Ogg, etc., following definition given above).
2. Enter encoding options for that format.
   *The user may stop at this step, which would satisfy use case (1).*
3. Save the selected format and options to a *profile*, giving it a name.
   *This further step satisfies cases (2) and (3).*

For these steps, a suitable dialog box may be one with a drop-down menu for the format, such that a change to the selection in this menu changes the controls for specifying encoding options, and populates them with statically-defined initial values. Once the user selects from this menu (step 1), the user may change the options values (step 2). Finally, if desired, the user may save the values to a profile (step 3), using an additional set of buttons. Support also would be needed for restoring values from a saved profile.

As you correctly observe, the current structure supports all of the use case. It lacks support for changing the format of a profile after it is created, but you correctly observe also that the need for such support is very minimal. However, the current design additionally lacks support for simply completing steps (1) and (2) without engaging the application components which involve step (3). Inconvenience results from the mental burden of separating the two categories of items, formats and profiles, while maintaining them in some constructed, mixed category that you are calling *format*.

Ultimately, it is unlikely that the difference would have any consequence more severe than inconvenience. The same users will use the application, and will succeed in the same use cases. How much you care about this difference depends on you, but I think the argument is strong that the application would be more natural to use with a different layout.

**Comment by brainchild0** [comment]
@AO-LocLab: Thanks, just a few comments:

- To be clear, I support the objective of avoiding confusion for the user who wants the simple use case, but I also doubt any conflict between this objective and a clearer layout.
- I am not necessarily suggesting adding an entirely new dialog box only for managing profiles. I believe that saving and loading profiles can be managed in the same location as specifying encoding options. (There may be a case, however, for creating a new box in place of the tab in the *Preferences*.)
- If the user is able to select a target format without dealing with profiles, then no need continues  for default profiles. I think  this effect is valuable.

**Comment by brainchild0** [comment]
Below is shown an attempt to illustrate a possible appearance for the interface for selecting encoding options. It is given in a separate dialog box, for simplicity of illustration, but the contents may be integrated into the existing *Preferences* box. The formats are presented in a drop-down box for brevity, but  of course may be shown in a sidebar, as they are currently.  File naming options are also omitted for simplicity.

The *Saved Profiles* text is shown with a checkbox due to limitations in the software used to generate the sketch. The intention is to express the possibility that the profile controls are given in a collapsible panel, following the earlier suggestion that it remain possible to hide them for simplicity to users not interested in the feature.

---

![flaconencoding](https://user-images.githubusercontent.com/34869175/84454001-62d43d80-ac27-11ea-9f99-d6c8d43932ce.png)

**Comment by SokoloffA** [comment]
I am confused, we are discussing several qestions at once.
1. UX for the main form - how many controls are needed and how the user selects the profile.
2. Naming - Format, Profiles, Audio formats or something else.
3. Preferences dialog.

I suggest to focus on the first. It doesn't make sense to discuss the second question until we decide on the first one. The first question is more important than the third, because the main form is used much more often than the settings dialog. 
After UX, we will select appropriate the name. Then we'll discuss the preferences dialog.

**So, the main form UX**
I don't mind changes to the interface. My main wish is that the user can switch profiles on one click. 

At the time, I suggested such a mockup, 
![mockup](https://user-images.githubusercontent.com/854935/67633589-bd9c6d00-f8c2-11e9-84b9-5ed66cb41bfd.png)
but now I think that having 2 controls for the profile and for the format is pointless. IMO user for converting should to select a profile and presses start. And the profile already contains all required settings, path and template for output files, format and it's quality settings, resampling settings and output CUE settings. Now, the template and path for the output files are keeps per profile, so these fields are not needed on the main form. 
Perhaps we should to simplify the form as much as possible? 
![Flacon](https://user-images.githubusercontent.com/854935/84687892-15b5db80-af47-11ea-94d2-9e2128de147d.png)


What do you think?

**Comment by brainchild0** [comment]
I was trying to leave options open for where to place the controls and what to call the items. Currently encoding options are in the *Preferences* box, but it was simpler for me to draw a separate box.

Concerning layout, could you have  separate menus for profile and format, and apply the following rules?:

- If the user selects a profile, set the value of the format to the one saved in that profile.
- If the user selects a format, clear the value of the profile.

**Comment by brainchild0** [comment]
If a user could save profiles, then it would also be useful to invoke the profile from the command line. A simple and useful example of a command-line invocation might have three arguments, with the effect of scanning an input directory (1) for source files, and writing results to some target directory (2), following a named profile (3).

**Comment by SokoloffA** [comment]
Having an option to specify a profile makes sense. I will do it.

**Comment by brainchild0** [comment]
It might be helpful to consider the interface design in [HandBrake](https://github.com/HandBrake/HandBrake). In many ways HandBrake is analogous to Flacon for video rather than audio discs.  The input in either case is a disc or image, and the output is a series of files that are easy to use in software media players. 

HandBrake comes loaded with a large number of "presets", and any modification may be saved, imported, or exported as a custom preset.

It may not be necessary to jump directly into an interface with the same complex design as that of Handbrake, but since it has so much widespread use, the design may be valuable as inspiration.

**Comment by SokoloffA** [comment]
Oh, no! I hate programs with an interface similar to the cockpit of a Boeing. May be I'm  idiot, but I've never been understand how to use such programs.

HandBrake
![HandBrake](https://academy.izi.travel/wp-content/uploads/TCV_01.jpg)

mpeg SQUARED
![mpeg SQUARED](https://cdn.8d9.ru/program_screenshoot/0005/84/thumb_483646_program_screenshoot_big.png)

MediaCoder
![MediaCoder](https://www.videohelp.com/softwareimages/mediacoder_880.jpg)


When an IDE or CAD has a complex UI & UX, it is justified, people use it full day, and specifically learn to use this applications. But utilities like Flacon are not used 8 hours per day.

The ideology of the Flacon is to have simple UI and UX. So that a user unfamiliar with the audio encoding can get the result in 2 clicks.

**Comment by brainchild0** [comment]
Yes, I understand the hesitation about complicating the interface beyond the  original intention of the design.

I have a few observations, including the following:

1.  HandBrake running on my system presents a much simpler UI design (see below), compared to the one you have shown, though still more complicated than that of Flacon. In fact, considering the very high number of options associated with splitting and transcoding the content of a video disc, it seems to me that the the UI I am showing is rather effective at hiding most of them away from the main section of the interface. The options visible when the first tab is open are limited to those options related to the selection of a "preset", files names,  format,  and chapter range.
     
2.  My reference to HandBrake was not intended to suggest a full adaptation toward the same style of interface, only to provide a source of inspiration. I intended to draw attention  primarily to the concepts related to encoding formats (i.e. general codec, separate from encoder options) and preset. In HandBrake, each preset corresponds to one format, each format may be used by any number of presets, and the default listing of presets covers a  variety of use cases more comprehensive than differences merely different formats. It may be valuable to consider whether some of these concepts would adapt well to the improvements being considered for Flacon.

Despite any objections to specific features of the design of HandBrake, the popularity of the application makes them worthwhile to consider seriously.  

---

![Screenshot from 2021-06-14 17-52-29](https://user-images.githubusercontent.com/34869175/121969726-e0eb8880-cd42-11eb-9589-a9a6d2d4c717.png)
