### ISSUE TITLE
support NRG images

### ISSUE THREAD

**Issue by nmz787** [flacon/flacon#149]
I have an audio CD image from 15-20 years ago, and wish to play and/or convert to audio files. This program doesn't seem to support images like this.

**Comment by SokoloffA** [comment]
I need more information to identify the problem.
1. What operating system you are use?
2. If Linux, then check that all the necessary programs are installed (Main menu -> Settings -> Preferences -> Programs)
3. Run the program from the console, you will get more information.

I was wondering what is the format on your CD. Upload the CD image and the CUE file. And send me a link. I'll see what the problem is.

**Comment by SokoloffA** [comment]
There is no response for a long time, so I close the issue. 
If you have additional information, feel free to open the issue.

**Comment by nmz787** [comment]
There was no CUE file associated with the NRG file. I ended up using this
solution:
https://unix.stackexchange.com/a/634657

**Comment by SokoloffA** [comment]
I see little misunderstanding. 

NRG and ISO are image of a disk, in your case an audio CD. An audio CD was created in the pre-computer era, and unlike a CD-ROM, it does not contain a file system with files. Instead, it contains a continuous stream of raw audio data.
To extract audio tracks from a CD, you need to use the [CD ripper program](https://en.wikipedia.org/wiki/CD_ripper). These programs read the raw audio stream from a CD and save it as a computer audio file. Some audio players have similar functionality.

The Flacon not a ripper. My program reads not a disk image, but a music file (WAV, Flac). 
I see little misunderstanding, instead of creating separate per-track audio files, the entire album is saved as one large audio file. This is an ordinary audio file, the same as you listen in a music player, but its duration is equal to the entire album. Also text file is saved, which contains the start time of each track. This file is called CUE. My program takes this large audio file and CUE, and creates per-track audio files.

So
* To start, try opening your ISO in your favorite music player, maybe it will allow you to save tracks to files. 
* If I'm not mistaken, [clementine](https://www.clementine-player.org) supports this functionality.
* Some CD wrier programs support this, for example [K3b](https://en.wikipedia.org/wiki/K3b)
* Try looking for a CD-ripper program.
* At last, I think you can do this in the console.
