### ISSUE TITLE
Where are the files?

### ISSUE THREAD

**Issue by hobieorris** [flacon/flacon#151]
I set my directory for result files to a directory in my home account. I click on convert in flacon and see that it is extracting and encoding the source files successfully.  When I look in my result directory, there is nothing there.  What happened?  I am using Linux Mint.

**Comment by SokoloffA** [comment]
I'm sorry for the long silence. I didn't see a notification about your issue maybe Google marked the email as spam.

Running in the console with the "--debug " option will give you more information.

I need more information, send me your configuration file (~/.config/flacon/flacon.conf).

**Comment by SokoloffA** [comment]
Do you use flatpak version?

**Comment by audiomuze** [comment]
I'm guessing your files are located in a similar fashion to what's reported here:

https://github.com/flacon/flacon/issues/167

**Comment by SokoloffA** [comment]
> I'm guessing your files are located in a similar fashion to what's reported here:
> #167

Hardly, your problem is related to embedded CUE.
But hobieorris opened the bug report in April, at that time the program did not contain support for the embeded CUE. 

Most likely, the problem is related to the [security restrictions for Flatpack](https://github.com/flacon/flacon/issues/116#issuecomment-961438940). I hope the problem has already been fixed. Unfortunately, there is no feedback from hobieorris.

**Comment by hobieorris** [comment]
Tried it again with ver. 9.5.1 and it works fine!
