### ISSUE TITLE
FLAC %A  %a %d/%n - %t produces wrong output

### ISSUE THREAD

**Issue by andrewwong2000** [flacon/flacon#197]
I'm having an issue with "Artist" vs "Album Performer"

<img width="1656" alt="Screenshot 2023-03-20 at 8 36 26 pm" src="https://user-images.githubusercontent.com/20747889/226340716-63f32bde-c70f-4be3-a74e-c58524c6208e.png">

Notice how the artist is Beethoven, but if I use %a it inserts the Artist Performer Claudio Arrau

Appreciate advice on how to fix this. Thanks !

**Comment by SokoloffA** [comment]
This is expected behavior, artist tags may vary for tracks in one album, but you most likely want to have all the tracks in one directory. So I use Album performer tag.

Another thing is that the name of the menu item "Insert Artist" is incorrect. It was left over from earlier versions, and does not correspond to reality.

**Comment by SokoloffA** [comment]
Included in release 11.0.0
