### ISSUE TITLE
Debian repository not updated

### ISSUE THREAD

**Issue by Mte90** [flacon/flacon#60]
As you can see on http://download.opensuse.org/repositories/home:/Sokoloff/Debian_7.0/ there is the 3.1.1 version but the last one is 4.0.
It is possible to update it?

**Comment by SokoloffA** [comment]
Unfortunately, I can't do that. Since 1.0.0 the program requires Qt5.

Debian Wheezy does not contain [packages for Qt5](https://packages.debian.org/search?suite=wheezy&searchon=names&keywords=qtbase5-dev). Support Qt5 was added only in  [wheezy-backports](https://packages.debian.org/search?suite=wheezy-backports&searchon=names&keywords=qtbase5-dev)

As I understood from [this page](https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets), build.opensuse.org does not support wheezy-backports, only pure wheezy.

**Comment by Mte90** [comment]
I am using Debian Sid and I have already Qt5 but pretty sad about it, I will see a way to get the latest version.

**Comment by SokoloffA** [comment]
I do not understand you. Sid is a supernova, testing release. But according to Wikipedia, Debian 7 is oldoldstable Wheezy, released in 2013, and its support ended in 2016. 
I have [flacon 4.0.0 packages for Debian 9](http://download.opensuse.org/repositories/home:/Sokoloff/Debian_9.0/)

---

I tried to collect the package when released 4.0.0.
But failed fiasco, получил ошибку ["nothing provides qtbase5-dev, nothing provides qttools5-dev-tools"](https://build.opensuse.org/project/monitor/home:Sokoloff?arch_i586=1&defaults=0&repo_Debian_7_0=1&unresolvable=1)

**Comment by Mte90** [comment]
In that page https://flacon.github.io/download/ the Debian 9.0 are not available.
I will swtich the repo now :-D

**Comment by SokoloffA** [comment]
Oh, that's my mistake! I forgot to update the "download" page. I'll do it today.

**Comment by SokoloffA** [comment]
I updated web page, so I'm closing the issue.
If you have additional information, you are free to reopen this bug.
