### ISSUE TITLE
Incorrect handling of non english character sets in track file names

### ISSUE THREAD

**Issue by virtualviolet** [flacon/flacon#63]
When converting to flac format (might affect all) flacon doesn't appear to handle non english characters properly.

For example:

Correct naming: 

Fous De La Mer -  Ode à L'amour

What actually happens is it names the file like this:

Fous De La Mer - Ode � L'Amour.flac (invalid encoding)

If I double check the cue file, it contains:

TRACK 12 AUDIO
    TITLE "Ode à L'Amour"
    PERFORMER "Fous De La Mer"
    INDEX 01 55:33:34

**Comment by SokoloffA** [comment]
What codepage you use?
![flacon1](https://user-images.githubusercontent.com/854935/38780351-a8e5a442-40dd-11e8-8360-2a443c9756eb.png)

Perhaps you need to select correct codepage by hand. When you select "Auto detect", the program tries to determine the codepage of the CUE file automatically, but unfortunately, it does not always work, because the titles of song are too short. Try to choose the appropriate codepage manually.

If it's not helping, send me your CUE-file and screenshot  of the program.

**Comment by virtualviolet** [comment]
I have tried both auto and UTF-8.

If I manually edit the details in flacon, the non english characters
display ok and the filenames are correct

**Comment by SokoloffA** [comment]
Looks like that the CUE file isn't in Unicode, but 8 bit encoding (possibly Windows 1252 or Latin1).

**Comment by virtualviolet** [comment]
ah ok, thanks, let me try that

**Comment by virtualviolet** [comment]
That solved it :-)
