### ISSUE TITLE
Flacon on Linux Mint don't work

### ISSUE THREAD

**Issue by bameylan** [flacon/flacon#70]
I try to convert .ape files (with .cue) to .mp3 files. Nothing. I have this comment: [Decoder]&nbsp;Can't&nbsp;read&nbsp;189265440&nbsp;bytes
every time I try (also with WAV, AAC etc.)

Bernard

**Comment by SokoloffA** [comment]
What version of the program do you use?
Do you have a "mac" program installed?
Make sure the APE file isn't broken. Run the following command on terminal:
```mac your_ape_file.ape out.wav -d```

**Comment by Eonfge** [comment]
Can reproduce with the following setup

- Ubuntu: 18.04 LTS
- Flacon: 4.1.0-1bionic (provided by ppa:flacon)
- mac: 3.99-u4-b5-s7-1bionic

.ape files are otherwise in tact. They can be played with certain players, but I rather have multipart flac files.

Converting them using ffmpeg from the command line also works. This is thus a possible workaround:
https://askubuntu.com/questions/756800/batch-convert-and-split-ape-with-cue-to-flac-in-various-folders-from-terminal

**Comment by Eonfge** [comment]
Decompressing (-d) and verifying (-v) using mac does give a Error: 1009.

**Comment by SokoloffA** [comment]
>Decompressing (-d) and verifying (-v) using mac does give a Error: 1009.

If the mac returns an error, the audio file is broken. 
Players plays broken files, they just skip the spoiled pieces. Converters are stricter to quality of files.

**Comment by SokoloffA** [comment]
If you think the file's good, send it to me.
