### ISSUE TITLE
Retina display and Dark Theme are not supported

### ISSUE THREAD

**Issue by gshustin** [flacon/flacon#88]
1. Retina display is not supported yet
2. Dark theme on Mojave MacOS is not supported yet

MacBook Pro (Retina, 13-inch, Late 2013)
13.3-inch (2560 x 1600)
Intel Iris 1536 MB graphics
MacOS Mojave 10.14.3

**Comment by SokoloffA** [comment]
I added [Retina support](https://github.com/flacon/flacon/commit/c45848faa4532291894b3377fc956367009e0c08).

I've prepared the program for a dark theme. But for now it's disabled because Qt has a issue with the dark theme. 
![image](https://user-images.githubusercontent.com/854935/54954785-847ed180-4f5c-11e9-86d4-223d00575a97.png)

There's an [bug in the bugtracker](https://bugreports.qt.io/browse/QTBUG-68850), I hope they fix it soon, and I can enable dark theme support.

**Comment by gshustin** [comment]
Great, thanks a lot. It's definitely the best free app for mac!
Retina and dark theme support will be appear in the next version? Because there are no updates yet.

**Comment by SokoloffA** [comment]
Retina support will be in the next release. I plan to release it in the coming days.
Support of the dark theme don't, I'm waiting for updates from the Qt guys.

**Comment by gshustin** [comment]
Thanks a lot!
